/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *HossamPC
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "stm32_f103c6_GPIO.h"
#include "stm32_f103c6_USART.h"
int x;
#define gg()   x=321;
int flag;

void clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}


unsigned char ch;

int main(void)
{
	clock_init();
	USART_config U_cfg;

	U_cfg.Baud_rate=USART_BaudRate_115200;
	U_cfg.HW_Flow_Control=USART_Flow_Control_NONE;
	U_cfg.IRQ_Enable=USART_IRQ_ENABLE_NONE;
	U_cfg.P_IRQ_Callback=NULL;
	U_cfg.Parity=USART_Parity_NONE;
	U_cfg.Payload_length=USART_Payload_Length_8;
	U_cfg.Stop_bits=USART_Stop_bit_1;
	U_cfg.USART_MODE = USART_MODE_TX_RX;

	MCAL_USART_Init(USART1, &U_cfg);
	MCAL_USART_GPIO_Set_Pins(USART1);
	while(1){
		MCAL_USART_Receive_Data(USART1, &ch, enable);
		MCAL_USART_Send_Data(USART1, &ch, enable);
	}
}
