/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *HossamPC
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "stm32_f103c6_GPIO.h"
#include "stm32_f103c6_USART.h"
#include "stm32_f103c6_SPI.h"
int x;
//#define MCU_ACT_as_Master
#define MCU_ACT_as_Slave
int flag;

void clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}


unsigned char ch;
GPIO_PinConfig_t Pincfg;

void SPii_IRQ(struct SPI_IRQ_SRC irq_src)
{
#ifdef MCU_ACT_as_Slave
	if(irq_src.RXNE)
	{
		ch=0xf;
		MCAL_SPI_TX_RX(SPI1, &ch, pollingdisable);
		MCAL_USART_Send_Data(USART1, &ch, enable);
	}
#endif
}


void test_IRQ(void){
#ifdef MCU_ACT_as_Master
	MCAL_USART_Receive_Data(USART1, &ch, disable);
	MCAL_USART_Send_Data(USART1, &ch, enable);
	//spi
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN4, 0);
	MCAL_SPI_TX_RX(SPI1, &ch, pollingenable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN4, 1);
#endif

}

int main(void)
{
	clock_init();
	USART_config U_cfg;

	U_cfg.Baud_rate=USART_BaudRate_115200;
	U_cfg.HW_Flow_Control=USART_Flow_Control_NONE;
	U_cfg.IRQ_Enable=USART_IRQ_ENABLE_RXNEIE;
	U_cfg.P_IRQ_Callback=test_IRQ;
	U_cfg.Parity=USART_Parity_NONE;
	U_cfg.Payload_length=USART_Payload_Length_8;
	U_cfg.Stop_bits=USART_Stop_bit_1;
	U_cfg.USART_MODE = USART_MODE_TX_RX;

	MCAL_USART_Init(USART1, &U_cfg);
	MCAL_USART_GPIO_Set_Pins(USART1);
	//==========================
	SPI_config spi_cnfg;
	spi_cnfg.Comm_Mode=SPI_COMM_MODE_2LINES_TX_RX;
	spi_cnfg.Data_size=SPI_DATA_SIZE_8_BIT;
	spi_cnfg.Clock_Phase=SPI_CLOCK_PHASE_FIRST_EDGE;
	spi_cnfg.Clock_Polarity=SPI_CLOCK_POLARITY_HIGH_WHEN_IDLE;
	spi_cnfg.Frame_Format=SPI_FRAME_MSB_FIRST;
	spi_cnfg.SPI_Clock_Freq=SPI_BAUD_RATE_PRESCALER_8;
#ifdef MCU_ACT_as_Master
	spi_cnfg.IRQ_Enable=SPI_IRQ_ENABLE_NONE;
	spi_cnfg.Device_Mode=SPI_DEVICE_MODE_MASTER;
	spi_cnfg.P_IRQ_Callback=NULL;
	spi_cnfg.NSS=SPI_NSS_SOFTWARE_INTERNAL_SS_SET;

	//config PA4
	Pincfg.GPIO_PinNumber=GPIO_PIN4;
	Pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	Pincfg.GPIO_Output_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA, &Pincfg);

	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN4, 1);
#endif

#ifdef MCU_ACT_as_Slave
	spi_cnfg.IRQ_Enable=SPI_IRQ_ENABLE_RXNIE;
	spi_cnfg.Device_Mode=SPI_DEVICE_MODE_SLAVE;
	spi_cnfg.NSS=SPI_NSS_HARDWARE_SLAVE;
	spi_cnfg.P_IRQ_Callback=SPii_IRQ;

#endif

	MCAL_SPI_Init(SPI1, &spi_cnfg);
	MCAL_SPI_GPIO_Set_Pins(SPI1);



	while(1){
	}
}
