/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdio.h"
#include "stdint.h"
#define RCC 0x40021000
#define GPIOA 0x40010800
#define RCC_APB2ENR *(volatile uint32_t *) (RCC + 0x18)
#define GPIOA_CRH *(volatile uint32_t *) (GPIOA + 0x04)
#define GPIOA_ODR *(volatile uint32_t *) (GPIOA + 0x0C)
#define RCC_CFGR *(volatile uint32_t *) (RCC + 0x04)


typedef union {
    volatile uint32_t all;
    struct
    {
        volatile uint16_t reserved :13;
        volatile uint16_t pin13 :1;
    } Pin;

} R_ODR_t;

volatile R_ODR_t *R_ODR = (volatile R_ODR_t*)(GPIOA+0x0C);

int main()
{
	  RCC_CFGR |= (0b101 << 11);
	  RCC_CFGR |= (0b100 << 8);
    RCC_APB2ENR |= (1<<2);
    //init_Gpio
    GPIOA_CRH &= 0XFF0FFFFF;
    GPIOA_CRH |= 0X00200000;
    while (1)
    {
        int i;
        R_ODR->Pin.pin13=1;
        for (i = 0; i < 5000; i++);
        R_ODR->Pin.pin13=0;
        for (i = 0; i < 5000; i++);
    }
}

